<a href="https://colab.research.google.com/github/BrennZA/ZTM-ML/blob/main/Copy_of_numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [ ]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [ ]:
# Create a 1-dimensional NumPy array using np.array()
first_dimension = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
second_dimension = np.array([[4, 5, 6],
                             [7, 8, 9]])

# Create a 3-dimensional Numpy array using np.array()
third_dimension = np.array([[[1, 2, 3],
                             [4, 5, 6]],

                            [[7, 8, 9],
                             [10, 11, 12]]])


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [ ]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
first_dimension.shape, first_dimension.ndim, first_dimension.dtype, len(first_dimension), type(first_dimension)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [ ]:
# Attributes of 2-dimensional array
second_dimension.shape, second_dimension.ndim, second_dimension.dtype, len(second_dimension), type(second_dimension)

((2, 3), 2, dtype('int64'), 2, numpy.ndarray)

In [ ]:
# Attributes of 3-dimensional array
third_dimension.shape, third_dimension.ndim, third_dimension.dtype, len(third_dimension), type(third_dimension)

((2, 2, 3), 3, dtype('int64'), 2, numpy.ndarray)

In [ ]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(second_dimension,
                  index=['Player 1', 'Player 2'],
                  columns=['Round 1', 'Round 2', 'Round 3'])
df

Round 1  Round 2  Round 3
Player 1        4        5        6
Player 2        7        8        9

In [ ]:
# Create an array of shape (10, 2) with only ones
array_of_ones = np.ones([10, 2])
array_of_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
# Create an array of shape (7, 2, 3) of only zeros
array_of_zeros = np.zeros([7, 2, 3])
array_of_zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
# Create an array within a range of 0 and 100 with step 3
array_to_100 = np.arange(0, 100, 3)
array_to_100

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [ ]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_int_array = np.random.randint(10, size=[7, 2])
random_int_array

array([[3, 9],
       [7, 4],
       [6, 5],
       [4, 0],
       [9, 7],
       [0, 8],
       [0, 4]])

In [ ]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_float_array = np.random.rand(3, 5)
random_float_array

array([[0.16432238, 0.69986908, 0.48125411, 0.78114424, 0.44229117],
       [0.47052767, 0.29808619, 0.06853101, 0.09463532, 0.24465424],
       [0.55439228, 0.68529385, 0.67017596, 0.74362307, 0.98805794]])

In [ ]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_int_array_2 = np.random.randint(10, size=[4, 6])
random_int_array_2

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [ ]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_int_array_3 = np.random.randint(1, 10, size=[3, 7])
random_int_array_3

# Find the unique numbers in the array you just created
np.unique(random_int_array_3)

array([1, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
random_int_array_3_df = pd.DataFrame(random_int_array_3)
random_int_array_3_df

0  1  2  3  4  5  6
0  7  1  1  9  9  4  9
1  3  7  6  8  9  5  1
2  3  8  6  8  9  4  1

In [ ]:
# Find the 0'th index of the latest array you created
random_int_array_3[0]

array([7, 1, 1, 9, 9, 4, 9])

In [ ]:
# Get the first 2 rows of latest array you created
random_int_array_3[[0, 1], :]

array([[7, 1, 1, 9, 9, 4, 9],
       [3, 7, 6, 8, 9, 5, 1]])

In [ ]:
# Get the first 2 values of the first 2 rows of the latest array
random_int_array_3[[0, 1], :1]

array([[7],
       [3]])

In [ ]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_int_array_4 = np.random.randint(10, size=[3, 5])
random_int_array_4

array_of_ones_2 = np.ones([3, 5])
array_of_ones_2

random_int_array_4.shape, array_of_ones_2.shape

((3, 5), (3, 5))

In [ ]:
random_int_array_4

array([[2, 3, 6, 3, 8],
       [0, 7, 6, 1, 7],
       [0, 8, 8, 1, 6]])

In [ ]:
array_of_ones_2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Add the two arrays together
random_int_array_4 + array_of_ones_2

array([[3., 4., 7., 4., 9.],
       [1., 8., 7., 2., 8.],
       [1., 9., 9., 2., 7.]])

In [ ]:
# Create another array of ones of shape (5, 3)
array_of_ones_3 = np.ones([5, 3])
array_of_ones_3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
array_of_ones_2.shape, array_of_ones_3.shape

((3, 5), (5, 3))

In [ ]:
# Try add the array of ones and the other most recent array together
array_of_ones_2 + array_of_ones_3.T

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [ ]:
# Create another array of ones of shape (3, 5)
array_of_ones_4 = np.ones([3, 5])
array_of_ones_4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Subtract the new array of ones from the other most recent array
array_of_zeros_2 = array_of_ones_3 - array_of_ones_4.T
array_of_zeros_2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# Multiply the ones array with the latest array
too_many_arrays = array_of_ones_4 * array_of_zeros_2.T + array_of_ones_3.T + random_float_array
too_many_arrays

array([[1.16432238, 1.69986908, 1.48125411, 1.78114424, 1.44229117],
       [1.47052767, 1.29808619, 1.06853101, 1.09463532, 1.24465424],
       [1.55439228, 1.68529385, 1.67017596, 1.74362307, 1.98805794]])

In [ ]:
# Take the latest array to the power of 2 using '**'
too_many_arrays ** 2

array([[1.3556466 , 2.88955489, 2.19411374, 3.17247481, 2.08020381],
       [2.16245162, 1.68502777, 1.14175853, 1.19822648, 1.54916419],
       [2.41613537, 2.84021537, 2.78948774, 3.04022142, 3.95237436]])

In [ ]:
# Do the same thing with np.square()
np.square(too_many_arrays)

array([[1.3556466 , 2.88955489, 2.19411374, 3.17247481, 2.08020381],
       [2.16245162, 1.68502777, 1.14175853, 1.19822648, 1.54916419],
       [2.41613537, 2.84021537, 2.78948774, 3.04022142, 3.95237436]])

In [ ]:
# Find the mean of the latest array using np.mean()
np.mean(too_many_arrays)

1.4924572351362972

In [ ]:
# Find the maximum of the latest array using np.max()
np.max(too_many_arrays)

1.9880579362543225

In [ ]:
# Find the minimum of the latest array using np.min()
np.min(too_many_arrays)

1.068531014822404

In [ ]:
# Find the standard deviation of the latest array
np.std(too_many_arrays)

0.26528321039814234

In [ ]:
# Find the variance of the latest array
np.var(too_many_arrays)

0.07037518171914507

In [ ]:
# Reshape the latest array to (3, 5, 1)
np.reshape(too_many_arrays, (3, 5, 1))

array([[[1.16432238],
        [1.69986908],
        [1.48125411],
        [1.78114424],
        [1.44229117]],

       [[1.47052767],
        [1.29808619],
        [1.06853101],
        [1.09463532],
        [1.24465424]],

       [[1.55439228],
        [1.68529385],
        [1.67017596],
        [1.74362307],
        [1.98805794]]])

In [ ]:
# Transpose the latest array
too_many_arrays.T

array([[1.16432238, 1.47052767, 1.55439228],
       [1.69986908, 1.29808619, 1.68529385],
       [1.48125411, 1.06853101, 1.67017596],
       [1.78114424, 1.09463532, 1.74362307],
       [1.44229117, 1.24465424, 1.98805794]])

What does the transpose do?

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random_array_1 = np.random.randint(10, size=[3, 3])
random_array_2 = np.random.randint(10, size=[3, 2])

random_array_1.shape, random_array_2.shape

((3, 3), (3, 2))

In [3]:
# Perform a dot product on the two newest arrays you created
np.dot(random_array_1, random_array_2)

array([[99, 72],
       [34, 30],
       [47, 38]])

In [4]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
random_array_3 = np.random.randint(10, size=[4,3])
random_array_4 = np.random.randint(10, size=[4,3])

random_array_3.shape, random_array_4.shape

((4, 3), (4, 3))

In [5]:
# Perform a dot product on the two newest arrays you created
np.dot(random_array_3, random_array_4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [6]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
np.dot(random_array_3, random_array_4.T)

array([[ 49,  95,  77,  66],
       [ 40,  64,  50,  42],
       [ 57,  83,  80,  53],
       [ 67, 103,  96,  67]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [8]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
random_array_5 = np.random.randint(10, size=[5,4])
random_array_6 = np.random.randint(10, size=[5,4])

In [10]:
random_array_5

array([[9, 1, 6, 1],
       [4, 7, 8, 1],
       [8, 3, 4, 0],
       [9, 0, 5, 4],
       [4, 6, 6, 6]])

In [11]:
random_array_6

array([[5, 8, 5, 0],
       [9, 6, 5, 1],
       [9, 7, 4, 3],
       [2, 3, 7, 3],
       [7, 0, 4, 0]])

In [9]:
# Compare the two arrays with '>'
random_array_5 > random_array_6

array([[ True, False,  True,  True],
       [False,  True,  True, False],
       [False, False, False, False],
       [ True, False, False,  True],
       [False,  True,  True,  True]])

What happens when you compare the arrays with `>`?

In [12]:
# Compare the two arrays with '>='
random_array_5 >= random_array_6

array([[ True, False,  True,  True],
       [False,  True,  True,  True],
       [False, False,  True, False],
       [ True, False, False,  True],
       [False,  True,  True,  True]])

In [13]:
# Find which elements of the first array are greater than 7
random_array_5[random_array_5 > 7]

array([9, 8, 8, 9])

In [14]:
# Which parts of each array are equal? (try using '==')
random_array_5 == random_array_6

array([[False, False, False, False],
       [False, False, False,  True],
       [False, False,  True, False],
       [False, False, False, False],
       [False, False, False, False]])

In [15]:
# Sort one of the arrays you just created in ascending order
np.sort(random_array_6)

array([[0, 5, 5, 8],
       [1, 5, 6, 9],
       [3, 4, 7, 9],
       [2, 3, 3, 7],
       [0, 0, 4, 7]])

In [17]:
random_array_5

array([[9, 1, 6, 1],
       [4, 7, 8, 1],
       [8, 3, 4, 0],
       [9, 0, 5, 4],
       [4, 6, 6, 6]])

In [16]:
# Sort the indexes of one of the arrays you just created
np.argsort(random_array_5)

array([[1, 3, 2, 0],
       [3, 0, 1, 2],
       [3, 1, 2, 0],
       [1, 3, 2, 0],
       [0, 1, 2, 3]])

In [20]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(random_array_5)

0

In [21]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(random_array_5)

11

In [ ]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created


In [ ]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created


In [ ]:
# Create an array of normally distributed random numbers


In [ ]:
# Create an array with 10 evenly spaced numbers between 1 and 100


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.